repos:
  - repo: local
    hooks:
      - id: gitleaks
        name: gitleaks
        entry: gitleaks protect --staged --redact --verbose
        language: system
        pass_filenames: false
        stages: [pre-commit]
